# Copyright 2025 Vijaykumar Singh <singhvjd@gmail.com>
#
# Capability Configuration for DataAnalysis Vertical

vertical_name: dataanalysis

capabilities:
  - name: data_profiling
    capability_type: tool
    version: "1.0"
    description: Data profiling and statistics
    tags:
      - profiling
      - statistics
    handler_module: victor.dataanalysis.profiler
    handler_function: DataProfiler
    default_config:
      include_visualizations: true
      compute_correlations: true

  - name: visualization
    capability_type: tool
    version: "1.0"
    description: Data visualization and plotting
    tags:
      - visualization
      - charts
    handler_module: victor.dataanalysis.viz
    handler_function: Visualizer
    default_config:
      default_style: seaborn
      dpi: 100

  - name: statistical_analysis
    capability_type: workflow
    version: "1.0"
    description: Statistical testing and analysis
    tags:
      - statistics
      - testing
    handler_module: victor.dataanalysis.stats
    handler_function: StatisticalAnalyzer
    default_config:
      significance_level: 0.05
      correction_method: bonferroni
